package com.example.cesijeujura;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class AccueilCommercial extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AccueilCommercial() {
		VerticalLayout mainLayout = new VerticalLayout();
		HorizontalLayout HLayout = new HorizontalLayout();
		this.setCompositionRoot(mainLayout);
		Label lab = new Label("Gestion de projet");
		mainLayout.addComponent(lab);
		Button button = new Button("Ajouter Nouveau Projet");		
		HLayout.addComponent(button);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
	}

}
