package com.example.cesijeujura.IHM.devis;

import java.util.Date;
import java.util.List;

import com.example.cesijeujura.Entities.Client;
import com.example.cesijeujura.Entities.Composant;
import com.example.cesijeujura.Entities.Devis;
import com.example.cesijeujura.IEJB.ComposantIEJB;
import com.example.cesijeujura.IEJB.DevisIEJB;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.data.Item;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EditionComposant extends VerticalLayout {
	protected Label lblTitle;
	protected HorizontalLayout composantsLayout;
	protected Table composantTable;
	protected VerticalLayout buttonLayout;
	protected Button addButton;
	protected Button deleteButton;
	//protected ComboBox composantCombo;
	protected HorizontalLayout closeLayout;
	protected Button closeButton;


	private ComposantIEJB composantEJB;
	
	public EditionComposant(DevisIEJB devisEJB) {
		Design.read(this);
		addButton.setEnabled(true);
		addButton.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				Notification.show("Ajouter Composant",
						Type.TRAY_NOTIFICATION);
			}
		});
		
		deleteButton.setEnabled(true);
		deleteButton.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				Notification.show("Supprimer un Composant",
						Type.TRAY_NOTIFICATION);
			}
		});
		
		/*
		// Initialisation de la comboBox des composants
		List<Composant> composants = composantEJB.findAllComposant();
		composantCombo.removeAllItems();
		if (composants.size() > 0) {
			for (Composant c : composants) {
				composantCombo.addItem(c);
			}
		}

		composantCombo.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				//initialiseComposant();
			}
		});
		 	*/
				composantTable.setSizeFull();
				composantTable.setSelectable(true);

				composantTable.addContainerProperty("Composant", String.class, "");
				composantTable.addContainerProperty("Nombre", Double.class, "");



	}
}
