package com.example.cesijeujura.IHM.devis;

import com.example.cesijeujura.IHM.client.FicheClient;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FicheDevis extends VerticalLayout {
	protected VerticalLayout layoutGauche;
	protected HorizontalLayout layoutProjetClient;
	protected TextField projectName;
	protected TextField clientNum;
	protected HorizontalLayout layoutAjout;
	protected ComboBox typePiece;
	protected Button btnAjout;
	protected HorizontalLayout layoutTableau;
	protected Table tabItem;
	protected VerticalLayout layoutDroit;
	protected MenuBar etatProjet;
	protected DateField dateLancement;
	protected DateField datePreDevis;
	protected DateField dateDevis;
	protected Button btnFicheClient;

	public FicheDevis() {
		Design.read(this);
		MenuBar.Command projet = new Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
				
			}
		};
		
		MenuBar.Command predevis = new Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
				
			}
		};
		
		MenuBar.Command devis = new Command() {
			@Override
			public void menuSelected(MenuItem selectedItem) {
				
			}
		};
		
		etatProjet.addItem("Projet", projet);
		etatProjet.addItem("Pré-devis", predevis);
		etatProjet.addItem("Devis", devis);
		
		tabItem.setSizeFull();
		tabItem.setSelectable(true);
		tabItem.addContainerProperty("Type de pièces", String.class, "");
		tabItem.addContainerProperty("Nom", String.class, "");
		tabItem.addContainerProperty("Réference", String.class, "");
		tabItem.addContainerProperty("Surface", String.class, "");
		tabItem.addContainerProperty("Nb Portes", String.class, "");
		tabItem.addContainerProperty("Nb Fenetres", String.class, "");
		tabItem.addContainerProperty("Prix", String.class, "");
		
		
	}
}
