package com.example.cesijeujura.IHM.devis;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ListeDevisBureauEtudes extends VerticalLayout {
	protected TextField filedRecherche;
	protected Table tabDevis;
	protected Button btnOuvrir;
	protected Button btnModif;
	protected Button btnValider;
	protected Button btnSupprimer;

	public ListeDevisBureauEtudes() {
		Design.read(this);
	}
}
