package com.example.cesijeujura.IHM.devis;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ListeDevis extends VerticalLayout {
	protected Label titleLabel;
	protected HorizontalLayout layout;
	protected VerticalLayout searchLayout;
	protected Label searchAdvanceLabel;
	protected GridLayout searchAdvanceLayout;
	protected Label clientLabel;
	protected ComboBox clientCombo;
	protected Label etatLabel;
	protected ComboBox etatCombo;
	protected Button createButton;
	protected HorizontalLayout devisLayout;
	protected Table devisTable;
	protected VerticalLayout buttonLayout;
	protected Button openButton;
	protected Button modifButton;
	protected Button validateButton;
	protected Button deleteButton;

	public ListeDevis() {
		Design.read(this);
	}
}
