package com.example.cesijeujura.IHM.devis;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TraitementDevisView extends VerticalLayout {
	protected HorizontalLayout referenceHLayout;
	protected HorizontalLayout devisHLayout;
	protected Label referenceDevisLabel;
	protected TextField referenceDevisTF;
	protected HorizontalLayout clientHLayout;
	protected Label referenceClientLabel;
	protected TextField referenceClientTF;
	protected TabSheet traitementSheet;
	protected HorizontalLayout filesHLayout;
	protected Table filesTable;
	protected VerticalLayout buttonLayout;
	protected Button addButton;
	protected Button deleteButton;
	protected HorizontalLayout chiffrageHLayout;
	protected Table modulesTable;
	protected Button editerCompButton;
	protected GridLayout buttonsGLayout;
	protected Button traiterButton;
	protected Button saveButton;
	protected Button quitButton;

	public TraitementDevisView() {
		Design.read(this);
	}
}
