ALTER TABLE `piece` CHANGE `FK_ID_TYPE_PIECE` `TYPE_PIECE_ID` INT(11) NOT NULL;

ALTER TABLE `piece` CHANGE `FK_ID_PROJET` `PROJET_ID` INT(11) NOT NULL;

ALTER TABLE `projet` CHANGE `FK_IDCOMMERCIAL` `FK_IDCOMMERCIAL` INT(11) NULL;